---
title: "hw02"
author: "Arlo"
html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```


```{r load packages, warning =FALSE, message=FALSE}
library(gapminder)
library(dplyr)
library(tidyverse)
library(tibble)
library(DT)
library(rmarkdown)
library(ggplot2)
library(tidyselect)
```

# Excercise(s) 1

## (1.1)
```{r Exercise 1.1}
(gapminder_subset <- gapminder %>%
    filter(year == 1970:1979) %>%
       filter(country == "Comoros" | country == "Eritrea" | country == "France"))
```

## (1.2)

```{r Ex. 1.2}
  gapminder_subset %>%
    select(gdpPercap, country)

```

## (1.3)

```{r Ex. 1.3}
gapminder %>%
  arrange(country, year) %>%
  group_by(country) %>%
  mutate(lifeExp_inc= lifeExp - lag(lifeExp)) %>%
  filter(lifeExp_inc<0)

```

## (1.4)

```{r Ex. 1.4}
gapminder %>%
  group_by(country) %>%
  summarize(gdpPercap_max = max(gdpPercap))
```

## (1.5)

```{r Ex. 1.5}
gapminder %>%
  filter(country == "Canada") %>%
    ggplot(aes(gdpPercap, lifeExp)) +
      geom_point(colour = "dark green", alpha = 0.5) +
        theme_classic() +
      scale_x_log10("Canadian GDP/capita", labels = scales::dollar_format()) +
      ylab("Canadian Life Expectancy")

```
*****

# Exercise 2

```{r Exercise 2 (setup)}
(gapminder_2 <-select(gapminder, country, pop))
```

```{r 2: Quantitative dplyr exploration}
 gapminder_2 %>%
  group_by(country) %>%
  summarize(Pop_min = min(pop), Pop_max = max(pop), Pop_mean = mean(pop), Pop_std_dev = sd(pop)) %>%
 
  ggplot(aes(country, Pop_mean)) +
    geom_bar(stat = "identity", colour = "dark green", alpha = 0.5) +
    theme_classic()

```



```{r 2: Categorical dplyr exploration}
gapminder %>%
  group_by(continent) %>%
  summarize(Countries=n()) %>%
 
ggplot(aes(continent, Countries)) +
    geom_bar(stat = "identity", colour = "dark green", alpha = 0.5) +
    theme_classic()
  
```


# Exercise 3

```{r Exercise 3 (setup)}
trees
datatable(as.tibble(trees))
```

```{r 3: Trees scatter}
 ggplot(trees, aes(Girth, Volume)) +
    geom_point(colour = "dark green", alpha = 0.5) +
    theme_classic()
```

```{r 3: Diameter class dist.}
trees %>% 
  ggplot(aes(Girth)) +
  geom_histogram(binwidth = 2
                 , colour = "dark green", alpha = 0.5) +
  theme_classic() +
  xlab("Diameter")
```


